#
# Using a single Consul host is _highly_ discouraged, but yolo
#
consul:
    image: progrium/consul:latest
    command: -server -bootstrap -ui-dir /ui
    mem_limit: 256m
    ports:
    - 53
    - 8300
    - 8301
    - 8302
    - 8400
    - 8500
    dns:
       - 127.0.0.1
    restart: always

#
# Manually bootstrap the first instance, then...
# Scale this tier and each additional container/instance will automatically self-configure as a member of the cluster
#
couchbase:
    image: misterbisson/triton-couchbase:enterprise-3.0.3-r3
    links:
    - consul
    mem_limit: 4096m
    ports:
    - 8091
    - 8092
    - 11207
    - 11210
    - 11211
    - 18091
    - 18092
    restart: always

#
# Benchmarks, for fun and sparkles
#
benchmark:
    image: misterbisson/couchbase-cloud-benchmark
    command: start.bash
    links:
    - consul
    mem_limit: 1024m
    restart: always
