#
# Using a single Consul host is _highly_ discouraged, but yolo
#
consul:
    image: progrium/consul:latest
    command: -server -bootstrap -ui-dir /ui
    restart: always
    mem_limit: 128m
    ports:
        - 53
        - 8300
        - 8301
        - 8302
        - 8400
        - 8500
    dns:
       - 127.0.0.1

#
# Manually bootstrap the first instance, then...
# Scale this tier and each additional container/instance will automatically self-configure as a member of the cluster
#
couchbase:
    image: misterbisson/triton-couchbase:enterprise-3.0.3-r4
    restart: always
    mem_limit: 4096m
    links:
        - consul
    ports:
        - 8091
        - 8092
        - 11207
        - 11210
        - 11211
        - 18091
        - 18092
    environment:
        - CONSUL_HOST=http://consul:8500
        - COUCHBASE_SERVICE_NAME=couchbase
        - COUCHBASE_USER=Administrator
        - COUCHBASE_PASS=password

#
# A dummy client to create some load
#
# This container is is not configurable and expects the following:
# CONSUL_HOST=http://consul:8500
# COUCHBASE_SERVICE_NAME=couchbase
# COUCHBASE_USER=Administrator
# COUCHBASE_PASS=password
#
benchmark:
    image: misterbisson/couchbase-cloud-benchmark
    restart: always
    mem_limit: 1024m
    command: start.bash
    links:
        - consul
