#
# Using a single Consul host is _highly_ discouraged, but yolo
#
consul:
    image: progrium/consul:latest
    command: -server -bootstrap -ui-dir /ui
    mem_limit: 256m
    ports:
    - 53
    - 8300
    - 8301
    - 8302
    - 8400
    - 8500
    restart: always

#
# Manually bootstrap the first instance, then...
# Scale this tier and each additional container/instance will automatically self-configure as a member of the cluster
#
couchbase:
    image: misterbisson/triton-couchbase
    links:
    - consul
    mem_limit: 222g
    ports:
    - 8091
    - 8092
    - 11207
    - 11210
    - 11211
    - 18091
    - 18092
    restart: always

#
# Benchmarks, for fun and sparkles
#
benchmark:
    image: 0x74696d/pillowfight
    mem_limit: 8g
    restart: never
    links:
    - consul
    - couchbase
    environment:
    - MIN_SIZE=800
    - MAX_SIZE=800
    - THREADS=32
    - ITEMS=250000000
    - BATCH=5000
    - CYCLES=10000
    - SET_PCT=10
    - RATE_LIMIT=1000000
    command: benchmark.bash
