#
# Using a single consul host is _highly_ discourage, but yolo
#
consul:
    command: -server -bootstrap -ui-dir /ui
    image: progrium/consul:latest
    ports:
    - 53
    - 8300
    - 8301
    - 8302
    - 8400
    - 8500

#
# The first Couchbase container will bootstrap the cluster
# Scale this tier and each additional container will automatically self-configure as a member of the cluster
#
# The link to consule is blocked by DOCKER-409
#
couchbase:
    image: couchbase/server
    links:
    - consul:consul
    ports:
    - 8091
    - 8092
    - 11207
    - 11210
    - 11211
    - 18091
    - 18092

#
# Benchmark container goes here...
#